### ISSUE TITLE
Out of memory error on GPU 0

### ISSUE THREAD

**Issue by imohuan** [jm12138/CPM-Generate-Paddle#7]
# Question
GPU 0上出现内存不足错误。无法在GPU 0上分配50.000000MB内存，已分配11.999512 GB内存，可用内存仅为0.000000B。
这提示不对劲啊？是我哪里弄错了吗

# Error
```
(gpu) G:\level-2\Python\CPM-Generate-Paddle>python AI_Bot.py --pretrained_model .\CPM-LM.pdparams
W0928 15:25:03.815069 17204 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 10.2
W0928 15:25:03.824172 17204 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
正在加载模型，耗时需要几分钟，请稍后...
Traceback (most recent call last):
  File "G:\level-2\Python\CPM-Generate-Paddle\AI_Bot.py", line 25, in <module>
    state_dict = paddle.load(args.pretrained_model)
  File "E:\PythonEnv\gpu\lib\site-packages\paddle\framework\io.py", line 964, in load
    load_result[key] = _ndarray_to_tensor(
  File "E:\PythonEnv\gpu\lib\site-packages\paddle\framework\io.py", line 399, in _ndarray_to_tensor
    return paddle.to_tensor(obj)
  File "E:\PythonEnv\gpu\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\PythonEnv\gpu\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "E:\PythonEnv\gpu\lib\site-packages\paddle\fluid\framework.py", line 434, in __impl__
    return func(*args, **kwargs)
  File "E:\PythonEnv\gpu\lib\site-packages\paddle\tensor\creation.py", line 184, in to_tensor
    return paddle.Tensor(
RuntimeError: ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 50.000000MB memory on GPU 0, 11.999512GB memory has been allocated and available memory is only 0.000000B.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

 (at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:87)
```

**Comment by imohuan** [comment]
我内存就16个g， 默认已经使用了7g，不知道需要多少？
